---
abstract: 'DB_File emulator with SQLite backend'
author:
  - 'Mark A. Jensen'
build_requires:
  AnyDBM_File::Importer: '0'
  Module::Build: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SQLite_File
provides:
  SQLite_File:
    file: lib/SQLite_File.pm
    version: '0.050'
  SQLite_File::BTREEINFO:
    file: lib/SQLite_File.pm
  SQLite_File::HASHINFO:
    file: lib/SQLite_File.pm
  SQLite_File::RECNOINFO:
    file: lib/SQLite_File.pm
recommends:
  AnyDBM_File::Importer: '0'
requires:
  DBD::SQLite: '1.25'
  Fcntl: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=SQLite_File
  license: http://dev.perl.org/licenses/
  repository: http://github.com/majensen/sqlite_file.git
version: '0.050'
